Repository e0xextazy/nlp_huawei_new2_task, pull requests merged in 2022-11, with the labels that each got.

#21 add task description
  README.md
Labels: documentation

#23 change latex formula to images
  README.md
  images/accuracy.png
  images/exact_match.png
Labels: bug, invalid, wontfix

#24 Create LICENSE
  LICENSE
Labels: documentation, good first issue

#25 Update README.md
  README.md
Labels: documentation, enhancement

#26 Update README.md
  README.md
Labels: documentation

#28 Issue 5 catboost baseline
  .gitignore
  baseline_catboost/catboost.ipynb
  baseline_catboost/requirements.txt
Labels: enhancement

#27 Issues #18, #19 deleted nan and nan cleaning
  baseline_rnn/rnn.ipynb
  baseline_tfidf_logreg/logistic-regression-tfidf.ipynb
  train.csv
Labels: bug, wontfix

#29 added unique ids in data
  test-with-targets.csv
  test.csv
  train.csv
Labels: bug, wontfix
