Repository e0xextazy/nlp_huawei_new2_task, pull requests merged in 2022-12, with the labels that each got.

#33 Issue 7 baseline transformers
  baseline_transformers/dataset.py
  baseline_transformers/model.py
  baseline_transformers/requirements.txt
  baseline_transformers/trainer.py
  baseline_transformers/transformers.ipynb
Labels: enhancement, good first issue

#34 32 catboost code style
  README.md
  baseline_catboost/catboost.ipynb
  baseline_catboost/requirements.txt
  baseline_rnn/rnn.ipynb
  sample_submission.csv
  setup/download_data.sh
  setup/setup_catboost.sh
  setup/setup_lstm.sh
  setup/setup_tf_idf_logreg.sh
  setup/setup_transformers.sh
  test.csv
  train.csv
Labels: enhancement

#35 Update README.md
  README.md
Labels: documentation
